;;; early-init.el --- Hellmacs early initialization -*- lexical-binding: t; no-byte-compile: t; -*-

;; Copyright (C) 2026 petrolal <petrolalucas@gmail.com>
;;
;; Author: petrolal <petrolalucas@gmail.com>
;; URL: https://github.com/petrolal/hellmacs
;; License: GPL-3.0-or-later
;;
;; This file is part of Hellmacs.
;;
;; Hellmacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; Hellmacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;; This file is loaded before `package.el', before `init.el', and
;; before the first frame is created.  Everything here exists to
;; make startup fast and to keep the first frame from flashing
;; stock Emacs chrome before Hellmacs gets a chance to configure it.
;; Nothing in here should depend on a third-party package.

;;; Code:

;;; 1. Directory layout --------------------------------------------
;;
;; Defined here, first, because both the performance tuning below
;; and every file loaded after this one need to know where things live.
;;
;; Hellmacs keeps three kinds of files apart, following Doom Emacs and
;; the XDG base directory spec:
;;
;;   `hellmacs-dir'       the distribution itself (this git repo)
;;   `hellmacs-user-dir'  your config: init.el, config.el, custom.el
;;   `hellmacs-data-dir'  installed packages -- needed to run, but
;;                        regenerated by reinstalling
;;   `hellmacs-cache-dir' disposable: native-comp output, caches
;;   `hellmacs-state-dir' history, recent files, bookmarks, backups --
;;                        not essential, but can't be regenerated
;;
;; A named profile (`emacs --profile work', or HELLMACS_PROFILE=work)
;; gets a completely separate set of all four: ~/.config/hellmacs-work/,
;; ~/.local/share/hellmacs-work/, and so on. The same Hellmacs checkout
;; can then run several independent configs side by side.

(defconst hellmacs-dir
  (file-name-directory (file-truename (or load-file-name buffer-file-name)))
  "Root directory of the Hellmacs distribution.")

(defconst hellmacs-core-dir (expand-file-name "core/" hellmacs-dir)
  "Directory holding Hellmacs engine internals (bootstrap, package manager).")

(defconst hellmacs-modules-dir (expand-file-name "modules/" hellmacs-dir)
  "Directory holding user-facing Hellmacs feature modules.")

(defconst hellmacs-profile
  (let ((name (or (cadr (member "--profile" command-line-args))
                  (getenv-internal "HELLMACS_PROFILE"))))
    (unless (member name '(nil "" "default"))
      (unless (string-match-p "\\`[A-Za-z0-9_-]+\\'" name)
        (error "Invalid Hellmacs profile name %S (use letters, digits, - and _)" name))
      name))
  "Name of the active profile, or nil for the default one.
Set with `emacs --profile NAME' or the HELLMACS_PROFILE environment
variable (which `bin/hellmacs --profile NAME' sets). Each profile has
its own config, packages, caches and history.")

;; Emacs doesn't know --profile; consume it (and its value) so it isn't
;; treated as a file to open.
(push (cons "--profile" (lambda (_) (pop command-line-args-left))) command-switch-alist)

(defconst hellmacs--dir-name
  (if hellmacs-profile (concat "hellmacs-" hellmacs-profile) "hellmacs")
  "Name of Hellmacs' directories under ~/.config, ~/.local/share, etc.")

(defun hellmacs--xdg-dir (envvar fallback)
  "Return Hellmacs' subdirectory of $ENVVAR, or of FALLBACK if unset."
  (expand-file-name (concat hellmacs--dir-name "/") (or (getenv-internal envvar) fallback)))

(defvar hellmacs-user-dir
  (if-let* ((dir (getenv-internal "HELLMACSDIR")))
      (file-name-as-directory (expand-file-name dir))
    (let ((xdg (hellmacs--xdg-dir "XDG_CONFIG_HOME" "~/.config")))
      (if (or hellmacs-profile
              (file-directory-p xdg)
              (not (file-directory-p "~/.hellmacs.d/")))
          xdg
        (expand-file-name "~/.hellmacs.d/"))))
  "Your private configuration: init.el, config.el and custom.el.
The first of $HELLMACSDIR, ~/.config/hellmacs/ (or under
$XDG_CONFIG_HOME) and ~/.hellmacs.d/ that exists; defaults to
~/.config/hellmacs/. A named profile uses ~/.config/hellmacs-NAME/.
It's fine for it not to exist -- Hellmacs then runs with its
defaults. See `hellmacs-init-user-dir'.")

(defconst hellmacs-data-dir (hellmacs--xdg-dir "XDG_DATA_HOME" "~/.local/share")
  "Installed packages and other data Hellmacs needs to run.
Deleting it forces every package to be reinstalled on the next start.")

(defconst hellmacs-cache-dir (hellmacs--xdg-dir "XDG_CACHE_HOME" "~/.cache")
  "Disposable, regenerable files: native-comp output and package caches.
Safe to delete at any time.")

(defconst hellmacs-state-dir (hellmacs--xdg-dir "XDG_STATE_HOME" "~/.local/state")
  "History, recent files, bookmarks, undo history, backups and autosaves.
Not needed to run, but deleting it loses that history for good.")

(defvar hellmacs--initial-load-path (copy-sequence load-path)
  "`load-path' before Hellmacs or any package touched it: Emacs' own.
Used to tell whether a package is built into Emacs (`package!'s
:built-in \='prefer).")

(define-obsolete-variable-alias 'hellmacs-var-dir 'hellmacs-cache-dir "0.2")
(define-obsolete-variable-alias 'hellmacs-etc-dir 'hellmacs-state-dir "0.2")

(with-file-modes #o700
  (dolist (dir (list hellmacs-data-dir hellmacs-cache-dir hellmacs-state-dir))
    (unless (file-directory-p dir)
      (make-directory dir t))))

;;; 2. Startup performance: GC ---------------------------------------
;;
;; Emacs runs a GC check on every allocation, which adds up over the
;; hundreds of `require'/`load' calls a full startup performs. Raise
;; the threshold as high as possible for the duration of boot;
;; `hellmacs-core' restores a bounded runtime value once startup
;; finishes (see `hellmacs--restore-gc-h' there).

(defvar hellmacs--gc-cons-threshold (* 16 1024 1024)
  "GC threshold Hellmacs restores once startup completes.")
(defvar hellmacs--gc-cons-percentage 0.1
  "GC percentage Hellmacs restores once startup completes.")

(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 1.0)

;;; 3. Startup performance: file-name-handler-alist -------------------
;;
;; Consulted on every `require'/`load'/`expand-file-name' call to
;; check for TRAMP, compressed, or encrypted file names. Trimming it
;; during boot skips that check for the hundreds of local elisp files
;; Hellmacs loads at startup. (Skipped for the daemon, where startup
;; time matters less.)
;;
;; The gzip handler has to stay if this Emacs ships its own Lisp
;; compressed (some distributions do): libraries that exist only as
;; .el.gz couldn't be loaded otherwise. Emacs' Lisp is either all
;; compressed or not, so one file tells which.

(defvar hellmacs--file-name-handler-alist (copy-sequence file-name-handler-alist)
  "`file-name-handler-alist' as Emacs set it up, before Hellmacs trimmed it.")

(unless (daemonp)
  (setq file-name-handler-alist
        (unless (locate-file-internal "calc-loaddefs.el" load-path)
          (list (rassq 'jka-compr-handler hellmacs--file-name-handler-alist))))

  ;; Files named on the command line are opened during startup and may
  ;; be remote (TRAMP) or compressed, so they get the full list back.
  (define-advice command-line-1 (:around (fn args-left) hellmacs-file-handlers)
    (let ((file-name-handler-alist
           (if args-left hellmacs--file-name-handler-alist file-name-handler-alist)))
      (funcall fn args-left)))

  ;; Restore it for the session, merging rather than overwriting in case
  ;; something added a handler during startup.
  (add-hook 'emacs-startup-hook
            (lambda ()
              (advice-remove #'command-line-1 #'command-line-1@hellmacs-file-handlers)
              (setq file-name-handler-alist
                    (delete-dups (append file-name-handler-alist
                                         (copy-sequence hellmacs--file-name-handler-alist)))))
            101))

;;; 4. package.el: disabled in favor of Elpaca -------------------------
;;
;; Hellmacs bootstraps Elpaca itself (see `hellmacs-packages'). Letting
;; `package.el' also initialize at startup would scan and autoload a
;; redundant, conflicting package system for no benefit.

(setq package-enable-at-startup nil)

;;; 5. Native compilation ----------------------------------------------

;; The `native-compile' feature is present even when native compilation
;; can't actually work (e.g. libgccjit is missing). Some packages then
;; try to use it anyway; pretend it doesn't exist instead.
(when (and (featurep 'native-compile)
           (not (native-comp-available-p)))
  (setq features (delq 'native-compile features)))

(when (featurep 'native-compile)
  ;; Redirect .eln files out of `user-emacs-directory'/eln-cache (the
  ;; git checkout) and into the cache dir: they're regenerable, and
  ;; `hellmacs-cache-dir' stays the one thing that's always safe to
  ;; delete.
  (when (fboundp 'startup-redirect-eln-cache)
    (startup-redirect-eln-cache (expand-file-name "eln/" hellmacs-cache-dir)))
  ;; Compile asynchronously instead of blocking the editor, and don't
  ;; pop up a warnings buffer for every third-party package that trips
  ;; a (usually harmless) native-comp warning during first compile.
  (setq native-comp-async-report-warnings-errors 'silent
        native-comp-jit-compilation t
        native-comp-async-jobs-number
        (max 1 (if (fboundp 'num-processors) (/ (num-processors) 2) 2))))

;;; 6. UI: unset chrome before the first frame is drawn -----------------
;;
;; Setting these as frame parameters (rather than calling
;; `menu-bar-mode' etc. later from `init.el') avoids allocating the
;; widgets in the first place. That is both faster and prevents the
;; "flash" of a fully-chromed default frame before Hellmacs' own
;; config has a chance to run.

(setq default-frame-alist
      (append '((menu-bar-lines . 0)
                (tool-bar-lines . 0)
                (vertical-scroll-bars . nil)
                (horizontal-scroll-bars . nil))
              default-frame-alist))

;; Belt-and-suspenders: also set the minor-mode variables so a later
;; `make-frame' (e.g. a new frame opened mid-session) stays consistent
;; even if something toggles a mode instead of touching frame params.
(setq menu-bar-mode nil
      tool-bar-mode nil
      scroll-bar-mode nil
      tooltip-mode nil)

(setq inhibit-startup-screen t
      inhibit-startup-echo-area-message user-login-name
      initial-scratch-message nil
      inhibit-default-init t
      ;; Resizing the frame to match font metrics on every startup and
      ;; theme load is a measurable, avoidable cost; do it once.
      frame-inhibit-implied-resize t)

;; `inhibit-startup-echo-area-message' only works when set literally in
;; the user's init file, and even with `inhibit-startup-screen' Emacs
;; still does some of the splash screen's work. Skip both outright.
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore)
  (advice-add #'display-startup-screen :override #'ignore))

;;; 7. Miscellaneous startup and runtime settings -----------------------

;; `auto-mode-alist' is matched a second, case-insensitive time when
;; the first pass fails -- time wasted on every file opened. It only
;; requires patterns (and file names) to be properly cased.
(setq auto-mode-case-fold nil)

;; Warnings about packages redefining functions with the legacy advice
;; API aren't actionable, and each one triggers a redisplay.
(setq ad-redefinition-action 'accept)

;; Read subprocess output in 64KB chunks instead of 4KB. Language
;; servers and REPLs send a lot of it.
(setq read-process-output-max (* 64 1024))

;; Emacs 31 warns about every package file lacking a `lexical-binding'
;; cookie; users can't act on that for third-party packages.
(setq warning-inhibit-types '((files missing-lexbind-cookie)))

;; DEBUG=1 as an alternative to --debug-init, e.g. for bin/hellmacs:
;; more logging (`hellmacs-log') and backtraces on errors.
(when (member (getenv-internal "DEBUG") '("1" "t" "true" "yes"))
  (setq init-file-debug t
        debug-on-error t))

;; Site-wide defaults (site-start.el, default.el) almost always either
;; duplicate or actively conflict with a config as opinionated as a
;; full distribution's.
(setq site-run-file nil)

(provide 'early-init)
;;; early-init.el ends here
