;;; hellmacs-sync.el --- Install packages and write the synced profile -*- lexical-binding: t; -*-

;; `hellmacs-sync' is the equivalent of `doom sync'. Run it (usually as
;; `bin/hellmacs sync') whenever you change your `hellmacs!' block, a
;; packages.el, or a module's autoload.el. It:
;;
;;   1. reads your init.el's `hellmacs!' block and every packages.el
;;   2. installs and builds anything missing, through Elpaca
;;   3. writes a profile (see "Synced profile" in hellmacs-modules.el)
;;      so that startup can activate packages without Elpaca
;;
;; Startup notices when the profile is out of date and falls back to
;; activating packages live, so forgetting to sync slows startup down
;; but never breaks it.
;;
;; Not loaded at startup; `bin/hellmacs' and `M-x hellmacs-sync' load it.

;;; Code:

(require 'hellmacs-lib)
(require 'hellmacs-core)
(require 'hellmacs-packages)
(require 'hellmacs-keybinds)
(require 'hellmacs-modules)

(defun hellmacs-sync--log (format-string &rest args)
  "Report progress: FORMAT-STRING with ARGS, on stdout in batch mode."
  (let ((msg (apply #'format format-string args)))
    (if noninteractive
        (princ (concat msg "\n"))
      (message "Hellmacs sync: %s" msg))))

(defun hellmacs-sync--packages ()
  "Return the installed Elpaca records for every declared package.
Includes their dependencies, with each package after the packages it
depends on, so autoloads load in a safe order."
  (let (seen ordered)
    (cl-labels ((visit (id)
                  (unless (memq id seen)
                    (push id seen)
                    (when-let* ((e (elpaca-get id)))
                      (dolist (dep (elpaca--dependencies e))
                        (visit (car dep)))
                      (push e ordered)))))
      (pcase-dolist (`(,name . ,plist) (reverse hellmacs-packages))
        (when (hellmacs-package--order name plist)
          (visit name))))
    (nreverse ordered)))

(defun hellmacs-sync--autoloads-file (e)
  "Return the autoloads file Elpaca generated for package record E, or nil.
Follows the recipe's :autoloads, as `elpaca-activate' does."
  (let* ((recipe (elpaca<-recipe e))
         (member (plist-member recipe :autoloads))
         (key (if member (cadr member) t))
         (file (and key
                    (expand-file-name (if (stringp key) key
                                        (concat (elpaca<-package e) "-autoloads.el"))
                                      (elpaca<-build-dir e)))))
    (and file (file-exists-p file) file)))

(defun hellmacs-sync--make-autoload (form file)
  "Return the `autoload' form for definition FORM from FILE, or nil.
The function doing this was `make-autoload' until Emacs 30, and is
`loaddefs-generate--make-autoload' since. (`loaddefs-generate' itself
writes file names relative to its output file, which doesn't suit a
profile living outside the checkout.)"
  (funcall (if (fboundp 'loaddefs-generate--make-autoload)
               #'loaddefs-generate--make-autoload
             'make-autoload)
           form file))

(defun hellmacs-sync--module-autoloads ()
  "Return autoload forms for every `;;;###autoload' in modules' autoload.el.
A cookie before a definition yields an `autoload' form; before any
other form, the form itself is kept, as in Emacs' own loaddefs."
  (require 'loaddefs-gen)
  (let (forms)
    (dolist (key (hellmacs-module-list))
      (let ((file (expand-file-name "autoload.el" (hellmacs-module-get key :path))))
        (when (file-exists-p file)
          (with-temp-buffer
            (insert-file-contents file)
            (emacs-lisp-mode)
            (goto-char (point-min))
            (while (re-search-forward "^;;;###autoload[ \t]*$" nil t)
              (let ((form (read (current-buffer))))
                (push (or (hellmacs-sync--make-autoload form (file-name-sans-extension file))
                          form)
                      forms)))))))
    (nreverse forms)))

(defun hellmacs-sync--write (file header data)
  "Write DATA (a list of forms) to FILE, after the comment HEADER."
  (make-directory (file-name-directory file) t)
  (with-temp-file file
    (let ((print-length nil) (print-level nil) (print-circle nil)
          (print-escape-newlines t) (print-quoted t))
      (insert header "\n")
      (dolist (form data)
        (prin1 form (current-buffer))
        (insert "\n")))))

(defun hellmacs-sync--write-profile ()
  "Write the profile for the current modules and installed packages."
  (let* ((packages (hellmacs-sync--packages))
         (stamp (format ";; Generated by `hellmacs-sync' on %s; don't edit."
                        (format-time-string "%F %T"))))
    (hellmacs-sync--write
     (hellmacs-profile-file "module-autoloads.el")
     (concat ";;; module-autoloads.el -*- lexical-binding: t; no-byte-compile: t -*-\n" stamp)
     (hellmacs-sync--module-autoloads))
    ;; Written last: its presence means the rest of the profile is complete.
    (hellmacs-sync--write
     (hellmacs-profile-file "profile.eld")
     (concat ";; -*- mode: lisp-data -*-\n" stamp)
     (list (list :emacs-version emacs-version
                 :modules (hellmacs-profile--modules)
                 :inputs (hellmacs-profile--inputs)
                 :packages hellmacs-packages
                 :load-path (mapcar #'elpaca<-build-dir packages)
                 :autoloads (delq nil (mapcar #'hellmacs-sync--autoloads-file packages)))))
    packages))

;;;###autoload
(defun hellmacs-sync ()
  "Install every declared package, then write the synced profile.
Run it after changing your `hellmacs!' block, a packages.el, or a
module's autoload.el. Signals an error if a package fails to install."
  (interactive)
  ;; In a running session, packages may already be loaded from a synced
  ;; profile; tell Elpaca startup is over, so it doesn't warn about them.
  (when after-init-time
    (defvar elpaca-after-init-time)
    (setq elpaca-after-init-time (or (bound-and-true-p elpaca-after-init-time)
                                     after-init-time)))
  (hellmacs-sync--log "Reading modules and packages...")
  (hellmacs-modules-read-config)
  (hellmacs-sync--log "Modules: %s"
                      (mapconcat (lambda (m) (format "%s %s" (car (car m)) (cdr (car m))))
                                 (hellmacs-profile--modules) ", "))
  (hellmacs-sync--log "Installing and building packages (this can take a while)...")
  (hellmacs-modules-install-packages)
  (let ((failed (cl-loop for (name . plist) in hellmacs-packages
                         for e = (and (hellmacs-package--order name plist) (elpaca-get name))
                         when (and e (not (eq (elpaca<-status e) 'finished)))
                         collect name)))
    (when failed
      (error "These packages failed to install: %s. Run the sync again; \
if they keep failing, see M-x elpaca-log in Emacs"
             (mapconcat #'symbol-name failed ", "))))
  (let ((packages (hellmacs-sync--write-profile)))
    (hellmacs-sync--log "Synced %d packages; profile written to %s"
                        (length packages) (abbreviate-file-name hellmacs-profile-dir))
    (unless noninteractive
      (hellmacs-sync--log "done. Restart Emacs to start from the new profile."))))

(defun hellmacs-sync-batch ()
  "Entry point for `bin/hellmacs sync'. Exits Emacs with a status code."
  ;; early-init.el tuned these for an interactive boot, which a batch
  ;; session never finishes, so they'd never be restored.
  (setq file-name-handler-alist hellmacs--file-name-handler-alist
        gc-cons-threshold (* 128 1024 1024)
        gc-cons-percentage 0.1)
  (hellmacs-context-push 'cli)
  (condition-case err
      (progn (hellmacs-sync) (kill-emacs 0))
    (error
     (princ (format "Error: %s\n" (error-message-string err)))
     (kill-emacs 1))))

(provide 'hellmacs-sync)
;;; hellmacs-sync.el ends here
